name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn package --file app/pom.xml

      - name: Copy artifact
        run: |
          mkdir -p ${{github.workspace}}/drop
          cp -r app/target/*.?(war|jar) ${{github.workspace}}/drop

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{github.workspace}}/drop

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: testapp-koti
          slot-name: production
          package: ${{github.workspace}}/drop/*.jar
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          resource-group: ${{secrets.AZURE_RESOURCE_GROUP}}
          action: 'deploy'
